feat/Localization_28
RomanNikolaevich/laravel1 pull request #12
Opened 2022-12-17 04:22 UTC by RomanNikolaevich

2022-12-18 07:45 UTC, demelianenko-corcentric requested changes

2022-12-18 07:45 UTC, demelianenko-corcentric commented on app/Services/Admin/CurrencyService.php
>          $this->client = new Client([
Убери этот код из конструктора, т.к. он используется только в одном методе. Весь код. Если используешь только в одном методе, то это не нужно порождать постоянно. Лучше методе создать дополнительный для создания объекта. А переменные используются тоже только в одном методе. Зачем их постоянно записывать в свойства класса?

2022-12-18 07:45 UTC, demelianenko-corcentric commented on app/Services/Admin/CurrencyService.php
> +        $result = DB::table('currencies')->get();
Вот тут нужно выбрать один курс по коду и дате. У тебя не то. Сформируй where и  limit 1

2022-12-18 07:45 UTC, demelianenko-corcentric commented on app/Services/Admin/CurrencyService.php
> +        return 'There is no currency exchange rate according to the set parameters';
Плохая затея возвращать строку с ошибкой. Верни лучше null. Так ты в условиях можешь проверить нашло что либо или нет

2022-12-19 04:33 UTC, JokerVDen requested changes

2022-12-19 04:33 UTC, JokerVDen commented on app/Services/Admin/CurrencyService.php
> +			->first()
После вот этого метода будет или null или collection. Что будет если вызвать  метод от null? (null->someMethod())

2022-12-19 04:33 UTC, JokerVDen commented on app/Services/Admin/CurrencyService.php
> +		dd($currencyCollection);
Ну коммон. Я же говорил, чтоб не коммитил dd

2022-12-20 17:58 UTC, demelianenko-corcentric requested changes

2022-12-20 17:58 UTC, demelianenko-corcentric commented on app/Services/Admin/CurrencyService.php
> +			->pluck('rate')
get может вернуть null. Что будет в итоге? Попробуй вытянуть что нибудь не существующее в бд

2022-12-21 16:04 UTC, demelianenko-corcentric requested changes

2022-12-21 16:04 UTC, demelianenko-corcentric commented on app/Jobs/UpdateCurrencyJob.php
> +        $this->data = $data;
Date, не data

2022-12-21 16:04 UTC, demelianenko-corcentric commented on app/Services/Admin/CurrencyService.php
> +			return false;
Тут возвращай лучше null, или вообще выбрасцй эксепшн

2022-12-21 16:04 UTC, demelianenko-corcentric commented on app/Services/Admin/CurrencyService.php
> +			throw new Exception('There is no currency exchange rate according to the set parameters');
Тут просто null возвращай

2022-12-21 16:04 UTC, demelianenko-corcentric commented on app/Services/Admin/CurrencyService.php
> +		$currencyCollection->pluck('rate')
$collection->rate без pluck

2022-12-21 16:04 UTC, demelianenko-corcentric commented on app/Services/Admin/CurrencyService.php
> +			->get();
First

2022-12-21 16:04 UTC, demelianenko-corcentric commented on app/Services/Admin/CurrencyService.php
> +
Phpdoc

2022-12-21 16:04 UTC, demelianenko-corcentric commented on app/Models/Product.php
> +	public function getPriceForCount(): float|int
Это относится больше к ордеру. Или вынести это в сервис. Тут этой логики не должно быть

2022-12-21 16:04 UTC, demelianenko-corcentric commented on app/Jobs/UpdateCurrencyJob.php
> +		$currency = new CurrencyService();
app(Service::class)

2022-12-21 18:50 UTC, demelianenko-corcentric requested changes

2022-12-21 18:50 UTC, demelianenko-corcentric commented on app/Services/Admin/CurrencyService.php
> +		$rate = $currencyCollection->toArray()['rate']/$this->ratio;
Можно сразу ->rate,  без преобразования в массив

2022-12-21 18:50 UTC, demelianenko-corcentric commented on app/Models/Product.php
> +	public function getPriceForCount(): float|int
Ещё раз повторю - эта логика для ордера не для продукта!

2022-12-21 18:53 UTC, RomanNikolaevich commented on app/Models/Product.php
> +	public function getPriceForCount(): float|int
Причем тут ордер? Пользователь сменил валюту и у него на всем сайте цена должна измениться, а не только во время оформления покупки.

2022-12-22 06:35 UTC, demelianenko-corcentric requested changes

2022-12-22 06:35 UTC, demelianenko-corcentric commented on app/Console/Kernel.php
> +		//$schedule->job(UpdateCurrencyJob::class)->dailyAt('16:00');
В коммиты не зашиваем запомментированный код

2022-12-22 06:35 UTC, demelianenko-corcentric commented on app/Services/Admin/CurrencyService.php
> +			//ToDO: сделать перерасчет цены 'price' из таблицы 'products' в валюте $type по курсу из таблицы 'currencies'
Не сделал, тогда и функцию в ПР коммит не добавляй. Я не вижу, чтоб она где то использовалась

2022-12-22 06:35 UTC, demelianenko-corcentric commented on app/Http/Controllers/Api/Admin/CurrencyController.php
> +	public static function saveRates(): void
Название метода - updatRates. Сохраняй консистенцию

2022-12-22 06:35 UTC, demelianenko-corcentric commented on routes/api.php
> +		Route::get('currencies/save-rates', [CurrencyController::class, 'saveRates'])->name('currencies.save');
update-rates, метод контроллера updateRates, name - currencies.update_rate. Сохраняй консистенцию данных

2022-12-22 06:35 UTC, demelianenko-corcentric commented on postman_collection.json
> +							"raw": "http://localhost/api/currencies/save-rates?XDEBUG_SESSION_START=PHPSTORM",
в колекции постмена поменяй на update-rates

2022-12-22 06:38 UTC, demelianenko-corcentric requested changes

2022-12-22 06:38 UTC, demelianenko-corcentric commented on app/Console/Kernel.php
> +		$schedule->job(new UpdateCurrencyJob())->delay(Carbon::now()->addMinutes(1)->when(function () {
Ты же вроде параметром должен был прокидывать дату на которую курс получать?))

2022-12-22 13:20 UTC, merged