Feat/currency products m2
RomanNikolaevich/laravel1 pull request #14
Opened 2022-12-25 03:41 UTC by RomanNikolaevich

2022-12-26 08:02 UTC, demelianenko-corcentric requested changes

2022-12-26 08:02 UTC, demelianenko-corcentric commented on app/Services/Admin/CurrencyService.php
> +		return $convertPrice;
Принцип единой ответственности. У тебя метод выполняет 2 обязанности: находит продукт и конвертирует его цену. А из метода идёт: конвертировать цену. Т.е. сюда в метод ты должен передавать параметром не I'd рродукта, а его цену. И её просто конвертировать

2022-12-26 08:02 UTC, demelianenko-corcentric commented on app/Services/Admin/CurrencyService.php
> +		return $significant * (10 ** $exponent);
Пройтись по всем ретернам и сделай пустую строку перед ними

2022-12-26 08:02 UTC, demelianenko-corcentric commented on app/Services/Admin/CurrencyService.php
> +	public function getDefaultPriceFromDB(int $id): int|float|null
Это не ответственность этого класса. Он занимается только конвертацией. Он не должен ничего делать с продуктом. Он вообще о продукте ничего не должен знать

2022-12-28 06:58 UTC, demelianenko-corcentric approved these changes

2022-12-28 06:58 UTC, demelianenko-corcentric commented on app/Http/Controllers/Api/Admin/CurrencyController.php
> +		app(CurrencyService::class)->getCurrencyRateFromDB(\Carbon\Carbon::now(), 'EUR');
Вынеси в Use namespace карбона

2022-12-28 06:58 UTC, demelianenko-corcentric commented on app/Http/Controllers/Api/Admin/ProductController.php
> +        $products = $this->productService->getList(strtoupper($code));
Перенеси strtoupper в метод конвертации CurrencyService convertPrice, и в внутрь ProductService. Я тебе написал куда ниже

2022-12-28 06:58 UTC, demelianenko-corcentric commented on app/Http/Controllers/Api/Admin/ProductController.php
> +        $this->productService->show($product, strtoupper($code));
Тут тоже самое

2022-12-28 06:58 UTC, demelianenko-corcentric commented on app/Services/Admin/CurrencyService.php
> +        if (!empty(cache('rate_'.$code))) {
Вот тут бы приобразовывал touppercase. Метод выполняет две ответственности - получение из БД и из Кеша. Переименовывай в просто getRate этот метод

2022-12-28 06:58 UTC, demelianenko-corcentric commented on app/Services/Admin/CurrencyService.php
> +    public function getCurrencyRateFromDB(Carbon $date, ?string $code): float|bool|int|null
Код не может быть null, только string

2022-12-28 06:58 UTC, demelianenko-corcentric commented on app/Services/Admin/CurrencyService.php
> +        $defaultCode = config('currency.default_code');
И перед вот этой строкой преобразовател бы тоже к touppercase

2022-12-28 06:58 UTC, demelianenko-corcentric commented on app/Services/Admin/ProductService.php
> +    public function getList(?string $code): Collection
Код всегда прилетает строкой

2022-12-28 06:58 UTC, demelianenko-corcentric commented on app/Services/Admin/ProductService.php
> +            if ($code !== $defaultCode | null) {
Вот здесь делай преобразование touppercase, не в контроллере. Или null тебе тут не нужен. Только проверяй на ===

2022-12-28 06:58 UTC, demelianenko-corcentric commented on app/Services/Admin/ProductService.php
> +        if ($code === $defaultCode | null) {
Тут так же  | null  тебе не нужен

2022-12-28 08:53 UTC, RomanNikolaevich commented on app/Http/Controllers/Api/Admin/CurrencyController.php
> +		app(CurrencyService::class)->getCurrencyRateFromDB(\Carbon\Carbon::now(), 'EUR');
+

2022-12-28 08:54 UTC, RomanNikolaevich commented on app/Services/Admin/CurrencyService.php
> +    public function getCurrencyRateFromDB(Carbon $date, ?string $code): float|bool|int|null
+

2022-12-28 08:54 UTC, RomanNikolaevich commented on app/Services/Admin/ProductService.php
> +    public function getList(?string $code): Collection
+

2022-12-28 08:58 UTC, RomanNikolaevich commented on app/Services/Admin/ProductService.php
> +        if ($code === $defaultCode | null) {
+

2022-12-28 09:02 UTC, RomanNikolaevich commented on app/Services/Admin/ProductService.php
> +            if ($code !== $defaultCode | null) {
+

2022-12-28 09:05 UTC, RomanNikolaevich commented on app/Services/Admin/CurrencyService.php
> +        $defaultCode = config('currency.default_code');
+

2022-12-28 09:07 UTC, RomanNikolaevich commented on app/Services/Admin/CurrencyService.php
> +        if (!empty(cache('rate_'.$code))) {
+

2022-12-28 09:08 UTC, RomanNikolaevich commented on app/Http/Controllers/Api/Admin/ProductController.php
> +        $this->productService->show($product, strtoupper($code));
+

2022-12-28 09:08 UTC, RomanNikolaevich commented on app/Http/Controllers/Api/Admin/ProductController.php
> +        $products = $this->productService->getList(strtoupper($code));
+

2023-03-25 19:15 UTC, closed without merging