Feat/order api
RomanNikolaevich/laravel1 pull request #5
Opened 2022-12-11 14:25 UTC by RomanNikolaevich

2022-12-11 18:18 UTC, JokerVDen requested changes

2022-12-11 18:18 UTC, JokerVDen commented on app/Http/Requests/Orders/OrderUpdateRequest.php
> +            'id'  => 'integer' . $this->route()?->parameter('order')->id,
Не правильно. Ищи как поправить

2022-12-11 18:18 UTC, JokerVDen commented on app/Models/Category.php
> + * App\Models\Categories
?

2022-12-11 18:18 UTC, JokerVDen commented on app/Http/Requests/Orders/OrderUpdateRequest.php
> +            'user_id' => 'integer',
А user_id не должен ли быть в какой нибудь из таблицы, ну если передаётся?))

2022-12-11 18:18 UTC, JokerVDen commented on app/Http/Requests/Orders/OrderCreateRequest.php
> +            'user_id' => 'integer',
Чуть ниже про это поле написано

2022-12-12 03:21 UTC, JokerVDen commented on app/Http/Requests/Orders/OrderUpdateRequest.php
> +            'id'  => 'integer' . $this->route()?->parameter('order')->id,
Ты id передашь через get параметр. Тут его принимать не будешь. Можешь удалить

2022-12-12 03:22 UTC, JokerVDen commented on app/Http/Requests/Orders/OrderUpdateRequest.php
> +            'user_id' => 'integer',
unique, у тебя есть это в другом реквксте, только required не ставь, пользователь не всегда есть в заказе

2022-12-12 03:22 UTC, JokerVDen commented on app/Http/Requests/Orders/OrderCreateRequest.php
> +            'user_id' => 'integer',
Такая же байда, как и сверху

2022-12-12 03:24 UTC, JokerVDen commented on app/Models/Category.php
> + * App\Models\Categories
Читай какой неймспейс. При чём здесь реквест? Тут неймспейс модели

2022-12-12 19:00 UTC, demelianenko-corcentric approved these changes

2022-12-12 19:09 UTC, merged